export const stoneStageCollection = [
  { key: "first", title: "첫 돌 친구", unlockAt: 1 },
  { key: "friends", title: "돌 친구들", unlockAt: 5 },
  { key: "pile", title: "작은 돌무더기", unlockAt: 15 },
  { key: "pocket", title: "포근한 돌주머니", unlockAt: 25 },
  { key: "picnic", title: "조약돌 소풍", unlockAt: 35 },
  { key: "campfire", title: "모닥불 돌야영", unlockAt: 55 },
  { key: "basket", title: "돌바구니", unlockAt: 75 },
  { key: "stream", title: "반짝 돌개울", unlockAt: 95 },
  { key: "meadow", title: "민들레 돌들판", unlockAt: 110 },
  { key: "greenhouse", title: "조약돌 온실", unlockAt: 150 },
  { key: "rainPond", title: "빗방울 돌연못", unlockAt: 225 },
  { key: "cart", title: "돌수레", unlockAt: 300 },
  { key: "workshop", title: "돌친구 공방", unlockAt: 450 },
  { key: "bookNook", title: "고요한 돌책상", unlockAt: 550 },
  { key: "cafe", title: "돌친구 찻집", unlockAt: 700 },
  { key: "treeHouse", title: "새싹 돌나무집", unlockAt: 950 },
  { key: "observatory", title: "별빛 관측소", unlockAt: 1200 },
  { key: "moonCamp", title: "달빛 돌캠프", unlockAt: 1600 },
  { key: "garden", title: "곰돌이 돌정원", unlockAt: 2000 },
  { key: "festival", title: "별가루 돌축제", unlockAt: 2750 },
  { key: "bakery", title: "구름빵 돌가게", unlockAt: 3500 },
  { key: "village", title: "조약돌 마을", unlockAt: 5000 },
  { key: "rainbowMarket", title: "무지개 돌시장", unlockAt: 5500 },
  { key: "harbor", title: "고래구름 항구", unlockAt: 6000 },
  { key: "sparklePile", title: "별빛 돌언덕", unlockAt: 6500 },
  { key: "lighthouse", title: "별빛 돌등대", unlockAt: 7000 },
  { key: "bigBasket", title: "구름 돌바구니", unlockAt: 7500 },
  { key: "forestTrain", title: "보석숲 돌기차", unlockAt: 8000 },
  { key: "skyGarden", title: "구름 위 돌정원", unlockAt: 8500 },
  { key: "carriage", title: "달빛 돌마차", unlockAt: 9000 },
  { key: "starGarden", title: "별고래 돌정원", unlockAt: 10000 },
  { key: "dreamAquarium", title: "꿈결 돌수족관", unlockAt: 10250 },
  { key: "moonIsland", title: "달토끼 돌섬", unlockAt: 10500 },
  { key: "cloudLibrary", title: "구름 돌책방", unlockAt: 11000 },
  { key: "candyFountain", title: "별사탕 분수", unlockAt: 11500 },
  { key: "candyWorkshop", title: "별사탕 돌공방", unlockAt: 11750 },
  { key: "auroraStation", title: "오로라 정거장", unlockAt: 12000 },
  { key: "whaleTheater", title: "고래별 극장", unlockAt: 12500 },
  { key: "auroraPort", title: "오로라 돌항구", unlockAt: 12750 },
  { key: "galaxyBridge", title: "은하수 돌다리", unlockAt: 13000 },
  { key: "gemCamp", title: "보석숲 캠핑장", unlockAt: 13500 },
  { key: "starlightCamp", title: "별자리 돌야영지", unlockAt: 13750 },
  { key: "constellationPark", title: "별자리 놀이공원", unlockAt: 14000 },
  { key: "cloudOpera", title: "구름 위 돌극장", unlockAt: 14250 },
  { key: "goldenPalace", title: "황금구름 궁전", unlockAt: 14500 },
  { key: "skyCastle", title: "무지개 하늘성", unlockAt: 14750 },
  { key: "royalGarden", title: "왕실 별빛정원", unlockAt: 14850 },
  { key: "stoneKingdom", title: "돌친구 왕국", unlockAt: 15000 },
] as const;

export type StoneStageKey = "auto" | (typeof stoneStageCollection)[number]["key"];
export const allowedStoneStages = new Set<StoneStageKey>(["auto", ...stoneStageCollection.map((stage) => stage.key)]);
