export const stoneStageCollection = [
  { key: "first", title: "첫 돌 친구", scene: "●", unlockAt: 1 },
  { key: "friends", title: "돌 친구들", scene: "● ●", unlockAt: 5 },
  { key: "pile", title: "작은 돌무더기", scene: "●●●", unlockAt: 15 },
  { key: "pocket", title: "포근한 돌주머니", scene: "♡", unlockAt: 25 },
  { key: "picnic", title: "조약돌 소풍", scene: "▦ ☀", unlockAt: 35 },
  { key: "campfire", title: "모닥불 돌야영", scene: "♨ △", unlockAt: 55 },
  { key: "basket", title: "돌바구니", scene: "▤", unlockAt: 75 },
  { key: "stream", title: "반짝 돌개울", scene: "≈ ✦", unlockAt: 95 },
  { key: "meadow", title: "민들레 돌들판", scene: "✿ ✿", unlockAt: 110 },
  { key: "greenhouse", title: "조약돌 온실", scene: "⌂ ♧", unlockAt: 150 },
  { key: "rainPond", title: "빗방울 돌연못", scene: "☂ ≈", unlockAt: 225 },
  { key: "cart", title: "돌수레", scene: "▰ ○○", unlockAt: 300 },
  { key: "workshop", title: "돌친구 공방", scene: "⚒", unlockAt: 450 },
  { key: "bookNook", title: "고요한 돌책상", scene: "▤ ✎", unlockAt: 550 },
  { key: "cafe", title: "돌친구 찻집", scene: "♨ ♡", unlockAt: 700 },
  { key: "treeHouse", title: "새싹 돌나무집", scene: "♧ ⌂", unlockAt: 950 },
  { key: "observatory", title: "별빛 관측소", scene: "⌕ ✦", unlockAt: 1200 },
  { key: "moonCamp", title: "달빛 돌캠프", scene: "☾ △", unlockAt: 1600 },
  { key: "garden", title: "곰돌이 돌정원", scene: "✿ ♡", unlockAt: 2000 },
  { key: "festival", title: "별가루 돌축제", scene: "✦ ♫", unlockAt: 2750 },
  { key: "bakery", title: "구름빵 돌가게", scene: "☁ ♨", unlockAt: 3500 },
  { key: "village", title: "조약돌 마을", scene: "⌂ ⌂", unlockAt: 5000 },
  { key: "rainbowMarket", title: "무지개 돌시장", scene: "⌂ ⌁", unlockAt: 5500 },
  { key: "harbor", title: "고래구름 항구", scene: "⚓ ≈", unlockAt: 6000 },
  { key: "sparklePile", title: "별빛 돌언덕", scene: "✦ ● ✧", unlockAt: 6500 },
  { key: "lighthouse", title: "별빛 돌등대", scene: "▲ ✦", unlockAt: 7000 },
  { key: "bigBasket", title: "구름 돌바구니", scene: "☁ ▤", unlockAt: 7500 },
  { key: "forestTrain", title: "보석숲 돌기차", scene: "◆ ▰", unlockAt: 8000 },
  { key: "skyGarden", title: "구름 위 돌정원", scene: "☁ ✿", unlockAt: 8500 },
  { key: "carriage", title: "달빛 돌마차", scene: "☾ ▰", unlockAt: 9000 },
  { key: "starGarden", title: "별고래 돌정원", scene: "★ ✿", unlockAt: 10000 },
  { key: "dreamAquarium", title: "꿈결 돌수족관", scene: "≋ ◇", unlockAt: 10250 },
  { key: "moonIsland", title: "달토끼 돌섬", scene: "☾ ◠", unlockAt: 10500 },
  { key: "cloudLibrary", title: "구름 돌책방", scene: "☁ ▤", unlockAt: 11000 },
  { key: "candyFountain", title: "별사탕 분수", scene: "✦ ≋", unlockAt: 11500 },
  { key: "candyWorkshop", title: "별사탕 돌공방", scene: "✦ ⚒", unlockAt: 11750 },
  { key: "auroraStation", title: "오로라 정거장", scene: "⌁ ▰", unlockAt: 12000 },
  { key: "whaleTheater", title: "고래별 극장", scene: "◇ ♫", unlockAt: 12500 },
  { key: "auroraPort", title: "오로라 돌항구", scene: "⚓ ⌁", unlockAt: 12750 },
  { key: "galaxyBridge", title: "은하수 돌다리", scene: "✦ ═ ✦", unlockAt: 13000 },
  { key: "gemCamp", title: "보석숲 캠핑장", scene: "◆ △", unlockAt: 13500 },
  { key: "starlightCamp", title: "별자리 돌야영지", scene: "☆ △ ☆", unlockAt: 13750 },
  { key: "constellationPark", title: "별자리 놀이공원", scene: "☆ ◯", unlockAt: 14000 },
  { key: "cloudOpera", title: "구름 위 돌극장", scene: "☁ ♫", unlockAt: 14250 },
  { key: "goldenPalace", title: "황금구름 궁전", scene: "♕ ☁", unlockAt: 14500 },
  { key: "skyCastle", title: "무지개 하늘성", scene: "♜ ⌁", unlockAt: 14750 },
  { key: "royalGarden", title: "왕실 별빛정원", scene: "♕ ✿", unlockAt: 14850 },
  { key: "stoneKingdom", title: "돌친구 왕국", scene: "♛ ✦ ♛", unlockAt: 15000 },
] as const;

export type StoneStageKey = "auto" | (typeof stoneStageCollection)[number]["key"];
export const allowedStoneStages = new Set<StoneStageKey>(["auto", ...stoneStageCollection.map((stage) => stage.key)]);
